/**
 * This file was automatically generated by generate-entity-index.js file
 * You can disable the automatic generation by removing the prepare section of the workspace.json file under api section
 */

// item.entity.ts
export * from "./lib/item.entity"

// root.entity.ts
export * from "./lib/root.entity"

